drop table if exists band_name_genre_counts;
drop table if exists yay_nays;
drop table if exists band_names;
drop table if exists genres;

create table band_names
(
    id   integer primary key autoincrement,
    name text not null unique
);

create table genres
(
    id   integer primary key autoincrement,
    name text not null unique
);

create table band_name_genre_counts
(
    band_name_id integer not null,
    genre_id     integer not null,
    total        integer default 0,

    primary key (band_name_id, genre_id),

    foreign key (band_name_id) references band_names (id) on delete cascade,
    foreign key (genre_id) references genres (id) on delete cascade,

    unique (band_name_id, genre_id)
);

create table yay_nays
(
    band_name_id integer primary key,
    yay_count integer default 0,
    nay_count integer default 0,

    foreign key (band_name_id) references band_names (id) on delete cascade
);

insert into genres(name)
values ('Heavy Metal'),
       ('Alternative'),
       ('Rock n'' Roll'),
       ('Hard Rock'),
       ('Pop'),
       ('Classical'),
       ('Rock'),
       ('Progressive Rock'),
       ('Rap'),
       ('Thrash Metal'),
       ('Grunge'),
       ('Hip Hop'),
       ('Jazz'),
       ('Punk Rock'),
       ('Blues'),
       ('Pop Rock'),
       ('Alternative Metal'),
       ('Nu Metal'),
       ('Electronic'),
       ('R&B'),
       ('Country'),
       ('Psychedelic Rock'),
       ('Progressive Metal'),
       ('Melodic Death Metal'),
       ('Pop Punk'),
       ('Reggae'),
       ('Electronic Dance Music'),
       ('Video Game'),
       ('Punk'),
       ('Disco'),
       ('Black Metal'),
       ('Indie Rock'),
       ('Death Metal'),
       ('Dance'),
       ('Soul'),
       ('Folk'),
       ('Alternative Pop'),
       ('New Wave'),
       ('Power Metal'),
       ('Art Rock'),
       ('Indie Pop'),
       ('Rap Rock'),
       ('Blues Rock'),
       ('Emo'),
       ('Funk'),
       ('Techno'),
       ('Metalcore'),
       ('Synthpop'),
       ('Symphonic Metal'),
       ('Dubstep'),
       ('Experimental Rock'),
       ('Dance-Pop'),
       ('Indie'),
       ('Industrial Metal'),
       ('Acoustic Rock'),
       ('Soft Rock'),
       ('Gangsta Rap'),
       ('Trap'),
       ('50s Doo-wop'),
       ('Post-Hardcore'),
       ('Ambient'),
       ('Trance'),
       ('Soundtrack'),
       ('Kpop'),
       ('Christian'),
       ('Acoustic Pop'),
       ('Post-Grunge'),
       ('Industrial Rock'),
       ('Glam Metal'),
       ('East Coast Hip Hop'),
       ('Speed Metal'),
       ('World'),
       ('Gothic Rock'),
       ('Groove Metal'),
       ('Country Rock'),
       ('Synthwave'),
       ('Hardcore Punk'),
       ('Melodic Black Metal'),
       ('Contemporary R&B'),
       ('Arena Rock'),
       ('Alternative Hip Hop'),
       ('Doom Metal'),
       ('Electropop'),
       ('Rap Metal'),
       ('Neo-classical Metal'),
       ('K Pop'),
       ('Bubblegum Pop'),
       ('New Age'),
       ('Classic Country'),
       ('Teen Pop'),
       ('Post Punk'),
       ('Drum and Bass'),
       ('Alternative R&B'),
       ('Baroque'),
       ('Electronica'),
       ('Ska'),
       ('Old School Hip Hop'),
       ('Shoegaze'),
       ('House'),
       ('Electro-House');

insert into band_names(name)
values ('"Kevin!", Home Alone Mom'),
       ('....and we walked into the sea.'),
       ('...and the amazing nothingness'),
       ('4Skin'),
       ('A Glisten Party'),
       ('A quiet cancer'),
       ('Adult Themes'),
       ('Alan California'),
       ('Alan Sugar Armpits'),
       ('All Ryans and Brians'),
       ('Annie Gwenstiff'),
       ('Aunt Granny'),
       ('BB Lanket'),
       ('BJ & Spunken'),
       ('Ballet Sniper'),
       ('Ballsdeep Powerhouse'),
       ('Bam Bazooka'),
       ('Barbra Cadabra'),
       ('Barren Karrett'),
       ('Bedghost & Mayonaisse'),
       ('Beefout'),
       ('Beezer and the Beans'),
       ('Bennifer Jalopez'),
       ('Better Off with the Boltons'),
       ('Betty and the Sexy Buttholes'),
       ('Biccy Brains'),
       ('Big Dick Willy'),
       ('Billy Pigger'),
       ('Billy rocket'),
       ('Bitch Tits and the Bunny Boiler'),
       ('Bitches McNasty'),
       ('Blister Clit'),
       ('Boel Jellman'),
       ('Boke Boke Spaghetti'),
       ('Boker'),
       ('Bon Bons for the Boys'),
       ('Boomcock Schlong'),
       ('Boomer Mainy'),
       ('Boost Ghost'),
       ('Booster Moons'),
       ('Boston Hedgehogs'),
       ('Bothering Roderick'),
       ('Brandon Fartharder'),
       ('Brodown Hogs'),
       ('Bully McDickentits'),
       ('Bum Princess'),
       ('Bumper Crop a Beans'),
       ('Bunnyboiler Bitchslap'),
       ('Bureaulogical Nonchalance'),
       ('Buster Boots'),
       ('By the light of the amber lamps'),
       ('Cameltoe Jones'),
       ('Captain Crapstains'),
       ('Captain Suchacunt'),
       ('Carrie Couture'),
       ('Casualdejekyll formaldehyde'),
       ('Chablits'),
       ('Cherry Pickle'),
       ('Chicken Picadilly'),
       ('Chilli Reynolds'),
       ('Chuck Misery'),
       ('Chunder Bunny'),
       ('Clitoris Picnic'),
       ('Comfy punches'),
       ('Computers on the Internet'),
       ('Confetti Dinosaur'),
       ('Constance Neverender'),
       ('Constantly Never Happy'),
       ('Cool Bullies'),
       ('Cop Police'),
       ('Corny Sean and the Pickles'),
       ('Coughie Cops'),
       ('Coxley and Frottage'),
       ('Craic O''Kane'),
       ('Crapton'),
       ('Cripple Dick'),
       ('Cum Puns'),
       ('Cummie'),
       ('Custard Does Not Like'),
       ('D''Nastie Hoots'),
       ('DJ Basil Chives'),
       ('DJ Mayonaisse'),
       ('DJ Winkyfingers'),
       ('Dan Stanley'),
       ('Darwin Space Explosion'),
       ('Day Old Pocket Sausage'),
       ('Dead Sea Squirrels'),
       ('Deathly Bethshead'),
       ('Debased Thiccie'),
       ('Debbie Wendy Heavy Standing'),
       ('Define Casual'),
       ('Dennis the Menaces Nemisis'),
       ('Dick Flimsy'),
       ('Dick Picnic'),
       ('Dick Whiskey'),
       ('Dick suckin daddies'),
       ('Dickie Cumsock'),
       ('Dinky Dee and the Turtlenecks'),
       ('Dirty Sanchez and the Rusty Trombones'),
       ('Doctor Crocodile'),
       ('Doctor Psoriasis'),
       ('Dog Rumours'),
       ('Dr Fart Shittenpubes'),
       ('Dr Frankensteins Monster Phd'),
       ('Eggy IOU'),
       ('Elder Millenials'),
       ('Erotic Sanchez and the Kleptomaniacs'),
       ('Eufuckingidiot Doubtfire'),
       ('Everything''s Always Awful'),
       ('Ewey Yesimal'),
       ('Fakeghost'),
       ('Fangs a lot (vampire pun)'),
       ('Fanny Dickfucker'),
       ('Fart Intruder'),
       ('Fartin Maholeaff'),
       ('Farty Party Barbie'),
       ('Fat Jealous'),
       ('Fat Man Clams'),
       ('Father Brother Daughter Mother'),
       ('Fatso Horny'),
       ('Faux Fox'),
       ('Faux Jonty'),
       ('Feasting on feces'),
       ('Fingerman and the Quizzlepuff'),
       ('Fistulas at Dawn'),
       ('Fix Dicks'),
       ('Fizzy bizznezz'),
       ('Forever Never and Forever More'),
       ('Fox Problems'),
       ('Frank Wankenstein'),
       ('Frank Wanklin'),
       ('Frankenstein Wankenstain'),
       ('Frankie B Jesus'),
       ('Frenchie O''Toole'),
       ('Fuck poughkeepsie'),
       ('Fuckphilosopherz'),
       ('Fuckshit Shitake'),
       ('Fucky and the Fucksticks'),
       ('Gannett and the Gip'),
       ('Gasper'),
       ('Gavin Phantasm'),
       ('General Purpose and the Army of Things'),
       ('General Suddymaster'),
       ('German Trawler Porn'),
       ('Ghost Boots'),
       ('Ghost Spook Spectacular'),
       ('Ghouls OK'),
       ('Ginger Volta'),
       ('Ginny and the Tonics'),
       ('Girthy Girlfriend'),
       ('Gladly Loud-Pumps'),
       ('Glitter Dick'),
       ('God Damned Nick Brown'),
       ('Gothic Sphincter'),
       ('Gravery'),
       ('Ground Floor Flat'),
       ('Grundy Bunningtons'),
       ('Guff Guff Guffaw'),
       ('Gunny Robinson'),
       ('Hacksaw Jackson'),
       ('Hailey and the Mandlebrots'),
       ('Hairspray by Accident'),
       ('Happy Go Fuck Yourself'),
       ('Harry Hider and the Fuck Dogs'),
       ('Hate the hate the haters hatred hated'),
       ('Hecka Strangemin'),
       ('Hedgey Capers'),
       ('Helen Bach'),
       ('Helen Highwater'),
       ('Henry Nevernamed'),
       ('Henrys Ennui'),
       ('Herb Cilantro'),
       ('Hideous Idiot'),
       ('Hoover Sugar'),
       ('Horse Girl and the Theater Kids'),
       ('Huey and the Jackmans'),
       ('Huge Massive'),
       ('Hugo Fucking Jr.'),
       ('INeverKnewIWasButIAm'),
       ('IWishIWas ButICantBe'),
       ('Ian Sane'),
       ('Ich Bin Eine Queef Quaffer'),
       ('Icy Zee'),
       ('InSINNER8||'),
       ('Itchy Badger Patch'),
       ('Itchy Bits'),
       ('Jackson Solange'),
       ('Jalfrezis Comet'),
       ('James Hughes and the It''s OK Never Worries'),
       ('Janky Duvall'),
       ('Jasmine Queefwater'),
       ('Jazzy Queefs'),
       ('Jeffanie'),
       ('Jelly Deals'),
       ('Jennifer Tubsludge'),
       ('Jerful Kently'),
       ('Jersey D''vil'),
       ('Jimmy Jack and the Handsome Bastards'),
       ('Jizzy Queefs'),
       ('Joey Smithereen'),
       ('Jogon Walkitof'),
       ('Johannes Gafertzel'),
       ('John Merrick vs The Elephant Man'),
       ('Joke Nicholson'),
       ('Jort Goblin'),
       ('Jortimer'),
       ('Joybils'),
       ('Juan Toothree'),
       ('Judge Fudge and the Candy Canes'),
       ('Kedgeree'),
       ('Kevin Cynefin'),
       ('Kid Human'),
       ('Killer Be Killed'),
       ('Killiam William'),
       ('Kindly Gofuckyourself'),
       ('Kwilliam'),
       ('LG Beattie'),
       ('redvideocoffee'),
       ('Lady Blaze It'),
       ('Lardons'),
       ('Larry Falcondowner'),
       ('Lasagne Del Raymond'),
       ('Lil Boozy'),
       ('Limp dick pimps'),
       ('Lips Activity'),
       ('Lipsdick'),
       ('Littleriot Bigfight'),
       ('Loosely Spooks'),
       ('Lordeth Beige'),
       ('Lucifers Bejesus'),
       ('M''Lady Malady'),
       ('Macho Chubby'),
       ('Macho Pistachio'),
       ('Manthaniel'),
       ('Massive Beefer'),
       ('Mayor Maynot and the Squashy Kumquats'),
       ('McDicks'),
       ('McFace'),
       ('Millies Bee Syndrome'),
       ('Misty Magic and the Littermen'),
       ('Moidah! Moidah!'),
       ('Money Mayonnaise'),
       ('Motherfucking Filibuster'),
       ('Muddy Buddies'),
       ('My Current Unhappy Super Nintendo'),
       ('My Pornstar Name is Henry Thickens'),
       ('Necrotic Violins'),
       ('Nefarious rascal'),
       ('No Sign of the Arnolds'),
       ('Oak Boardland Reviews'),
       ('Old Billy Boots'),
       ('Old Man Dicker'),
       ('Oliver Mathematic'),
       ('Oliver Vehicles'),
       ('One pair of knickers short'),
       ('Oscars Proboscis'),
       ('Other people''s feces'),
       ('PJ Pussi'),
       ('Panica Tax'),
       ('Panicked Spastics'),
       ('Pause Gods'),
       ('Pee Pee and the Gonads'),
       ('Pending, in the quiet period.'),
       ('Pervy Pete and the Bellends'),
       ('Petey SD'),
       ('Phartz'),
       ('Phats Al-ami'),
       ('Piccadilly Lofts'),
       ('Picken Pockets'),
       ('Pickle Sanchez'),
       ('Picklefingers'),
       ('Pimp Doubt and the Jizzer Kicks'),
       ('Pipe Wife'),
       ('Piss cistern'),
       ('Piss holes in the snow'),
       ('Pistachio Mustachio'),
       ('Pizza Pants'),
       ('Plates Attenuate'),
       ('Portraits of Our Modern Selves'),
       ('Potemkins Lament'),
       ('Potential Future Epics'),
       ('Pretty Cathartic'),
       ('Professor Groupenpoop'),
       ('Pumpy Wanger'),
       ('Pun Fuckers'),
       ('QWERTY QWERTY queef queef'),
       ('Quarantitty Queens'),
       ('Queef Barista'),
       ('Queef Jackson'),
       ('Queef Latina'),
       ('Quickly Biscuits'),
       ('Quickly Queefs'),
       ('Quinoa Bean Bra'),
       ('Quinston'),
       ('Qweepy Kidz'),
       ('Racecourse Horse'),
       ('Rainbow Party Pro'),
       ('Reassuring Pats'),
       ('Reblacka Beck'),
       ('Richard Quadmind aka Dick 4 Brains'),
       ('Rickies Pish'),
       ('Ricky Ficticious'),
       ('Roquefort Chuff'),
       ('Rustic Fusty'),
       ('S''wedges'),
       ('Saint Francis Pants'),
       ('Saturday Squirtfest'),
       ('Sausage Mahoney'),
       ('Save Arseholes'),
       ('Sax Barlow'),
       ('Schniffin Beans'),
       ('Scraggly'),
       ('Scratchbacker'),
       ('Sellotape Mayhem'),
       ('Sexy Tripletease'),
       ('Shoiter'),
       ('Shortking Phantasmagoria'),
       ('Shovey Pushkin'),
       ('Shrugs Johnstone'),
       ('Slanty'),
       ('Slimmertough Strongbody'),
       ('Sniff Smell'),
       ('Snugly Fitz'),
       ('Sonny and the Dispositions'),
       ('Soup n Salad'),
       ('Space Machine Monkey Index'),
       ('Spaghetti Nonsense'),
       ('Spaghetti Tangents'),
       ('Spite House'),
       ('Spunk Markets'),
       ('Spunker'),
       ('Stein behind'),
       ('Steve Jobs vs the Secular Robot'),
       ('Stickola Nurgeon'),
       ('Stifflemass'),
       ('Sub Prime Superhero'),
       ('Sucker Puffy'),
       ('Sugarman Spookyface'),
       ('Super Chill and the Positive Effects'),
       ('Super Pretty Penis Party'),
       ('Super Self Loather'),
       ('Super ruined human'),
       ('Sushi Cushion'),
       ('Swage'),
       ('Swiss Rahul'),
       ('THE PFEFFERBEISSER BEATS'),
       ('Tarmac McCarthy'),
       ('Ten kick dicks'),
       ('The Beat Biff'),
       ('The Bokes'),
       ('The Bomb Seniors'),
       ('The Chinky Pimples'),
       ('The Cromulent Aether Witch'),
       ('The Dick Lickin’ Titties'),
       ('The Elastics'),
       ('The Foolish Nopes'),
       ('The Fuckhole Sphincters'),
       ('The Fucks Who Fuck and the Fuckers that Fuck Them'),
       ('The Garlic Gang'),
       ('The Jizzettes'),
       ('The Phlegms'),
       ('The Pipettes'),
       ('The Queefing'),
       ('The Quiet Slovakians'),
       ('The Shit Fitz'),
       ('The Shituations'),
       ('The Slaintes'),
       ('The Surfactants'),
       ('The Water Porridge'),
       ('The Window Hammers'),
       ('The casual sleights'),
       ('The dumb stubs'),
       ('The lasting consequences of brutalism'),
       ('The thing that happens to houses'),
       ('Thiccie Turd'),
       ('Thirsty Therapist'),
       ('Threader Pendragon'),
       ('Tiny Wine Drinker'),
       ('Tiny leviathans'),
       ('Toxic Sausage and the Revenge for Justice'),
       ('Trap Toutside'),
       ('Travis T'),
       ('Tubby Lardass'),
       ('Turnip Burps'),
       ('Ultra Cafe Baby'),
       ('Unfucking Ruiner'),
       ('Vanilla Flats'),
       ('VapeKween'),
       ('Varla Kebableon'),
       ('Vicky''s Phallus'),
       ('Viz Highbeam'),
       ('Wank Fuck'),
       ('Wanky Ribbons'),
       ('War Pipe'),
       ('Warren Peas'),
       ('Wax Looply and the Fruitcakes'),
       ('Weary Wives'),
       ('Wee Billy Buckus'),
       ('Whatever the French for Utopia Is'),
       ('Wilbur Wannafuck'),
       ('Willy Wontee'),
       ('Witch Haggis'),
       ('Witch Kitchen'),
       ('Witches Interesting'),
       ('Workhard Gerhardt'),
       ('Wyze Smartman'),
       ('Ya''Raspy Barrow'),
       ('batmichealwayne'),
       ('fox ache your egg hunt hour soul'),
       ('gloomymahoney'),
       ('heft'),
       ('helloghost'),
       ('lil queef'),
       ('spidersinsiderher'),
       ('squarepig go!');
